version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker login --username AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws/r6u8g8n9
      - REPOSITORY_URI=public.ecr.aws/r6u8g8n9/privaclave-container-images
      - CODEBUILD_RESOLVED_SOURCE_VERSION=1.0
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo Tagging Docker image...
      - docker tag privaclave-container-images:latest public.ecr.aws/r6u8g8n9/privaclave-container-images:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/r6u8g8n9/privaclave-container-images:latest
