version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker login --username ultimatixarup -p Passw9rd! ultimatixarup/testnode
      - CODEBUILD_RESOLVED_SOURCE_VERSION=1.0
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - echo Building the Docker image...
      - sudo docker build -t ultimatixarup/testnode/privaclave-container-images:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ultimatixarup/testnode/privaclave-container-images:latest
