version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login --region us-east-1 --no-include-email
      - $(aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r6u8g8n9)
      - REPOSITORY_URI=public.ecr.aws/r6u8g8n9/privaclave-container-images
      - CODEBUILD_RESOLVED_SOURCE_VERSION=1.0
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo Tagging Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
